spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/agrotoken}
    username: ${SPRING_DATASOURCE_USERNAME:agrotoken}
    password: ${SPRING_DATASOURCE_PASSWORD:agrotoken}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      idle-timeout: 600000
      max-lifetime: 1800000
      keepalive-time: 60000
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 10
  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8080

ollama:
  url: ${OLLAMA_URL:http://localhost:11434}
  model: llama3.2

agrotoken:
  solana:
    rpc-url: ${AGROTOKEN_SOLANA_RPC_URL:https://api.devnet.solana.com}
    program-id: ${AGROTOKEN_PROGRAM_ID:GM4oyeT5WV1mC1KVgwPMhUV4YMJw8e1i1GKkXMjYnvvY}
    oracle-wallet: ${AGROTOKEN_ORACLE_WALLET:FfzC9j1nC2P6GWmNRVQ16yJee3T1u3MRYuDKhXaphRLR}
    usdc-mint: ${AGROTOKEN_USDC_MINT:4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU}

